### ISSUE TITLE
Error: Cannot read property 'path' of undefined

### ISSUE THREAD

**Issue by mirgee** [katyo/publish-crates#74] opened 2021-01-08 16:35 UTC
Running the following, seemingly correct job (which mimicks [the usage example from the README](https://github.com/katyo/publish-crates#usage-examples))
```
jobs:
  publish-rust-wrapper:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --manifest-path wrappers/rust/Cargo.toml
          toolchain: stable
          override: true
      - uses: katyo/publish-crates@v1
        with:
          path: wrappers/rust
          dry-run: true
```
results in the following output
```
Searching cargo packages at 'wrappers/rust'
Found packages: wrapper-test
Checking packages consistency
Error: Cannot read property 'path' of undefined
```
This error is probably thrown downstream of [`checkPackages()`](https://github.com/katyo/publish-crates/blob/main/src/package.ts#L141), and is not a result of an issue with the published crate itself, as it can be successfully published locally. The same error is thrown when a crates.io token is used with `dry-run: false`.

**Comment by katyo** [comment] 2021-01-09 03:44
@mirgee Can you give me a link to full log of failed workflow run?

**Comment by mirgee** [comment] 2021-01-11 17:23
@katyo [This one](https://github.com/mirgee/indy-sdk/runs/1669618935?check_suite_focus=true), for example.

**Comment by katyo** [comment] 2021-01-12 06:12
@mirgee Seems the crate looks like workspace but the `indy-sys` subcrate does not listed in `workspace.members`.
By design workspace members only can be published.
Of course such behavior is wrong. The understandable error message should be thrown.

**Comment by katyo** [comment] 2021-01-18 18:21
@mirgee Can I close this issue?

**Closed** 2021-03-25 06:17 UTC
